////////////////////////////////////////
// Autogenerated Code, do not Modify! //
////////////////////////////////////////
#pragma once

#include <vector>
#include <string>

class PostProcess;
using FunctionPointer = bool (PostProcess::*)();

static const std::vector<std::pair<std::string, std::vector<FunctionPointer>>> postProcessData = {
    {"Center.json", {
        &PostProcess::Change_Language_For_Export_XML,
        &PostProcess::Update_Read_Only_Variables_With_Is_Values,
        &PostProcess::Show_Or_Hide_Logical_Units_By_Max_Number,
    }},
    {"LogicCircuit.json", {
        &PostProcess::Check_User_Curve_Names_And_Change_Data_Type,
        &PostProcess::Show_Or_Hide_Protections_Unit_And_Automatism,
        &PostProcess::Check_If_User_Curve_As_Good_Values_In_Is_Settings,
        &PostProcess::Check_Conditions_For_U49P,
        &PostProcess::Check_Conditions_For_U49T,
    }},
};
